### ISSUE TITLE
EventHandlerExists

### ISSUE THREAD

**Issue by Forlini91** [llde/Oblivion-Script-Extender#40]
We have SetEventHandler and RemoveEventHandler... but not a single method to check whatever an event handler exists.
SetEventHandler doesn't overwrite existing event handlers, so calling it multiple times with the same parameters will effectively register the same handler multiple times (and so the event will call the function multiple times).
Since we can't check whatever an event handler has already been registered, we're forced to destroy any possible existing handler with RemoveEventHandler and then registering it (again, if it was removed).

`<bool> EventHandlerExists <eventName::string> <function::ref> <filter1> <filter2>`
where <filter1> and <filter2> are optional.

**Comment by llde** [comment]
Added in commit [e19b9f1 ](https://github.com/llde/Oblivion-Script-Extender/commit/e19b9f1c7b8ddfeb01ea6c8dcb17914129608c1b). Forgot to close the issue
