### ISSUE TITLE
Non-redirected functions passed as args to redirected functions are auto-redirected

### ISSUE THREAD

**Issue by claustromaniac** [llde/Oblivion-Script-Extender#49]
Really sorry for the long title. It should be clear, though (I hope). When using this syntax to call a function...

`ref.FunctionName <Expression(s)>`

...any non-redirected function calls made as part of an OBSE expression and passed as arguments to that function are called on the same reference as the function in question (ref, in this case).

Example:
```
Let refVar := UrielSeptimRef
if GetSelf == PlayerRef
   refVar.Call SomeFunction (GetBaseObject)
   ;GetBaseObject in this context returns UrielSeptim, NOT Player.
endif
```
I guess for most people with an object-oriented programming background this is merely expected behaviour, but most modders don't have such a background. Redirecting function calls was already doable before OBSE, but it was the implementation of OBSE expressions that allowed modders to experience this behaviour, so I believe this is another bit of relevant info that is worth a mention in the docs. Perhaps in the existing section covering _Considerations_ for using OBSE expressions.

**Comment by shadeMe** [comment]
It's already mentioned in the the Call command's description:

> Call - calls a user-defined function. Should be followed by a list of arguments matching the types expected by the function. If a calling reference is specified, commands within the function body will operate on that reference. Call returns whatever value is returned by the function.

**Comment by claustromaniac** [comment]
*Facepalm*

I swear I didn't find it anywhere. I must have accidentally looked for that in the v20 documentation.

I guess this can be closed then.
