### ISSUE TITLE
NVidia drivers issues

### ISSUE THREAD

**Issue by Forlini91** [llde/Oblivion-Script-Extender#55]
Surely you heard about the issue with newest NVidia drivers. Unless a fix is made, the game will soon become unplayable for tons players, as they update their graphic card.

Alenet already made a fix, but it's only available to players who use OR.
Is it possible to include the fix directly in OBSE?
I think it's very important and should be available to anyone.

**Comment by llde** [comment]
Need to check what Alenet did inside OR. I have to wait he release the sourcecode. Still it should be possible if it doesn't use too much OR internals.

**Comment by shadeMe** [comment]
I'm wary of including a fix directly in the OBSE core, to be honest, as it falls out of the project's purview. Plugin support was precisely meant to address such situations. Perhaps Alenet could be convinced to release the fix as a standalone plugin.

**Comment by llde** [comment]
Alenet reported that the Nvidia issue seems to be resolved after a windows update.
